config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get  "/auth/:provider/callback", to: 'sessions#omniauth'
  get '/dashboard', to: 'dashboard#index'

  get '/meal_builder', to: 'meal_builder#index'
  post '/meal_builder', to: 'meal_builder#create'

  get '/food_search', to: 'food_search#index'

  get '/meal_rating',  to: 'meal_rating#index'
  patch '/meal_rating', to: 'meal_rating#update'

  resources :foods, only: [:destroy, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user_id, :current_user_name

  def current_user_id
    session[:user_id]
  end

  def current_user_name
    session[:name]
  end

  private

  def reset_meal(meal)
    cookies[:meal]&.clear
    cookies[:meal] = MealSerializer.new(meal).serializable_hash.to_json
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @today = DateTime.current.in_time_zone(Time.now.getlocal.zone)
    @meals = BackendFacade.get_meals(current_user_id)
    @graphs = BackendFacade.get_graphs(current_user_id)
  end
end

app/controllers/food_search_controller.rb
class FoodSearchController < ApplicationController
  def index
    @foods = BackendFacade.food_search(params[:search]) if params[:search]
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def create
    food_params = { food_id: params[:food_id], food_name: params[:food_name] }
    if cookies[:meal].blank?
      meal = Meal.new({})
    else
      meal_data  = JSON.parse(cookies[:meal], symbolize_names: true)[:data]
      meal       = Meal.new(meal_data, meal_data[:attributes][:foods])
    end
    meal.add_food_entry(food_params)
    reset_meal(meal)
    redirect_to(meal_builder_path)
  end

  def destroy
    meal_data  = JSON.parse(cookies[:meal], symbolize_names: true)[:data]
    meal       = Meal.new(meal_data, meal_data[:attributes][:foods])

    meal.remove_food_by_food_id(params[:id])
    reset_meal(meal)
    redirect_to(meal_builder_path)
  end
end

app/controllers/meal_builder_controller.rb
class MealBuilderController < ApplicationController
  def index
    return if cookies[:meal].blank?

    meal   = JSON.parse(cookies[:meal], symbolize_names: true)[:data]
    @foods = meal[:attributes][:foods]
  end

  def create
    if cookies[:meal].present?
      meal_data = JSON.parse(cookies[:meal], symbolize_names: true)[:data]
      meal = Meal.new(construct_meal_data(meal_data), meal_data[:attributes][:foods])
      reset_meal(meal)
      BackendService.new_meal(current_user_id, cookies[:meal])
      cookies[:meal].clear
      redirect_to dashboard_path
    else
      flash[:error] = 'Unable to create meal. Please add a food!'
      redirect_to meal_builder_path
    end
  end

  private

  def construct_meal_data(meal_data)
    meal_data[:attributes][:name]      = params[:meal_name]
    meal_data[:attributes][:meal_time] = params[:meal_time]
    {
      id: meal_data[:id],
      name: meal_data[:attributes][:name],
      meal_time: meal_data[:attributes][:meal_time]
    }
  end
end

app/controllers/meal_rating_controller.rb
class MealRatingController < ApplicationController
  def index
    @meals = BackendFacade.get_meals(current_user_id)
  end

  def update
    meals = params[:meal]
    rank = params[:rating].to_i
    if meals
      meals.each do |meal|
        meals_hash = { "rank": rank, "meal_id": meal.to_i }
        BackendService.update_meal(current_user_id, meals_hash)
      end
      redirect_to dashboard_path
    else
      flash[:error] = 'Unable to add ranking. Please select meals!'
      redirect_to meal_rating_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def omniauth
    auth_hash = request.env['omniauth.auth']
    email = auth_hash['info']['email']
    name = auth_hash['info']['name']
    access_token = auth_hash['credentials']['token']
    response = BackendFacade.login_user(email, name, access_token)
    session[:user_id] = response
    session[:name] = name
    redirect_to '/dashboard'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="container mt-5">
  <h1 class="text-center"><%= current_user_name %>'s Dashboard</h1>
<br>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <div id="todays-meals">
          <h3>Today's Meals - <%= @today.strftime('%B %d, %Y') %></h3>
          <br>
          <% if @meals.nil? || @meals.empty?%>
            <p>You haven't logged any meals yet today</p>
          <% else %>
            <% @meals.each do |meal| %>

            <div id="meal-<%= meal.id %>" class="card mr-4" style="">
              <div class="card-header">
                <h4><%= meal.name %> - <%= meal.meal_time.to_datetime.strftime('%l:%M %P') %></h4>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Rating: <% if meal.rank >= 0 %>
                  <%= meal.rank %>/10
                  <% else %>
                  No rating yet
                <% end %></li>
                <li class="list-group-item">Foods:
                <%= meal.food_names.join(', ') %></li>
              </ul>
            </div>
            <br>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-sm">
        <div class="container">
          <div class="row">
            <div class="col">
                <div class="text-center mx-4" >
              <%= button_to 'Add a meal', meal_builder_path, method: :get, class: "btn btn-secondary form-control mx-2"%>
              </div>
            </div>
            <div class="col">
                <div class="text-center mx-4" >
              <%= button_to 'Rate meals', meal_rating_path,  method: :get, class:"btn btn-secondary form-control mx-2" %>
            </div>
            </div>
          </div>
        </div>
        <br>
        <p>Your Highest Rated Foods</p>
        <div >
          <%= image_tag(@graphs["10_Highest"], :id => "top_10", :alt => "Graph displaying user's top 10 foods") %>
        </div>
        <br>
        <p>Your Lowest Rated Foods</p>
        <div >
          <%= image_tag(@graphs["10_Lowest"], :id => "bottom_10", :alt => "Graph displaying user's bottom 10 foods") %>
        </div>
      </div>
    </div>
  </div>

app/views/food_search/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Food Search</h1>
  <div class="d-flex justify-content-center">
    <%= form_with url: food_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :search, required: true %>
      <%= f.submit 'Search' %>
    <% end %>
  </div>

  <table class="table table-hover">
  <tbody>
    <% @foods&.each do |food| %>
    <tr id="food-<%= food.id %>">
      <td ><%= food.name %></td>
      <td ><%= button_to "Add to Meal", foods_path, params: {food_id: food.id, food_name: food.name} %></td>
    </tr>
      <% end %>
  </tbody>
</table>




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackrFrontend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <main>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/meal_builder/index.html.erb
<div class="container mt-5">
  <h2 class=" text-center">Meal Builder</h2>
  <div class="d-flex justify-content-center">
    <div class="card text-center " style="width: 60rem;">
      <div class="card-body">
        <h5 class="card-title">Your Meal</h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= button_to 'Add food', food_search_path, method: :get %></h6>
        <br>
        <div class="card-text">
          <table class="table table-hover">
            <tbody>
              <% @foods&.each do |food| %>
                  <tr id="food-<%= food[:food_id] %>">
                    <td>  <%= food[:food_name] %></td>
                    <td><%= button_to 'Delete', food_path(food[:food_id]), method: :delete %></td>
                  </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <%= form_with url: meal_builder_path, method: :post do |f| %>
          <div class="form-inline">
            <%= f.label     :meal_name, required: true%>
            <%= f.text_field     :meal_name, required: true, class: "", style:"height:38px" %>  &nbsp

            <%= f.label :meal_time, required: true, class: ""%>
            <%= f.datetime_field :meal_time, required: true, class: "", style:"height:38px"%> &nbsp
            <%= f.submit         'Save meal', class: "btn btn-outline-secondary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meal_rating/index.html.erb
<div class="container mt-5">
  <h3>Choose meals to rate</h3>
  <%= form_with url: meal_rating_path, method: :patch, local: true do |f| %>
    <% @meals.each do |meal| %>
      <div id="meal-<%= meal.id %>">
        <p><%= check_box_tag 'meal[]', meal.id %> <%= meal.name %>
          <% if meal.rank > 0 %>
            - Current rating: <%= meal.rank %></p>
          <% end %>
      </div>
    <% end %>
    <%= f.label :rating %>
    <%= f.number_field :rating, in: 1..10, step: 1.0 %>
    <%= f.submit "Submit Rating" %>
    <p>Scale: 1 = I feel terrible;  10 = I feel amazing</p>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container mt-5">
  <h1 class="text-center" style="font-size: 50px; color: #005689;">Snackr Trackr</h1>
  <h3 class="text-center" >The feel-good food trackr</h3>
  <br>
  <div class="text-center" >
    <%= button_to "Log in with Google", '/auth/google_oauth2', method: :get, class: "btn btn-secondary btn-lg align-center", style: "background-color: #ff895d;"  %>
  </div>
</div>